locals {
  lab_firewall_rules = {
    iap_ssh = {
      port          = "22"
      source_ranges = ["35.235.240.0/20"]
      description   = "Loop lab: allow IAP SSH to the observability VM"
    }

    http = {
      port          = "80"
      source_ranges = ["0.0.0.0/0"]
      description   = "Loop lab: allow HTTP to the observability VM"
    }
  }

  lab_rule_names = [
    for rule_key in keys(local.lab_firewall_rules) :
    "${var.environment}-loop-lab-${rule_key}"
  ]

  public_rule_ports = {
    for rule_key, rule in local.lab_firewall_rules :
    rule_key => rule.port
    if contains(rule.source_ranges, "0.0.0.0/0")
  }
}

resource "google_compute_firewall" "loop_lab_ingress" {
  for_each = local.lab_firewall_rules

  project     = var.project_id
  name        = "${var.environment}-loop-lab-${each.key}"
  network     = module.observability_vm.network_name
  description = each.value.description

  direction     = "INGRESS"
  priority      = 1000
  source_ranges = each.value.source_ranges
  target_tags   = ["observability-vm"]

  allow {
    protocol = "tcp"
    ports    = [each.value.port]
  }
}

output "loop_lab_rule_names" {
  description = "Names generated by the for expression."
  value       = local.lab_rule_names
}

output "loop_lab_public_rule_ports" {
  description = "Ports from firewall rules open to all IPv4 addresses."
  value       = local.public_rule_ports
}